baseurl: "/"
languageCode: "en-us"
title: "Sola Analytics"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

# permalinks:
#   note: "/note/:year/:month/:day/:slug/"
#   post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    # - name: Categories
    #   url: "categories/"
    #   weight: 3
    # - name: Tags
    #   url: "tags/"
    #   weight: 4
    # - name: Subscribe
    #   url: "index.xml"

params:
  description: "A website built through Hugo and R blogdown."
  footer: "Made with [Hugo](https://gohugo.io/) and [R blogdown](https://github.com/rstudio/blogdown). Inspired by [Hugo Xmin](https://github.com/yihui/hugo-xmin)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
